data_root: D:/MIMIC-CXR-JPG/
pairs_csv: /path/to/mimic_pair_questions.csv
meta_csv: /path/to/mimic_all.csv
keyinfo_json: /path/to/all_diseases.json
ckpt: /path/to/r50_mcc.tar

backbone: resnet50
head: classifier   # or decoder
dec_vocab: 6000

bs: 16
lr: 1.0e-4
epochs_mrm: 1
epochs_warmup: 1
epochs_vqa: 3
topk: 64

lambda_mrm: 0.1
lambda_align: 0.05
lambda_cf: 0.05
seed: 42
